### ISSUE TITLE
Erro ao cadastrar e credenciar usuário, consumindo API

### ISSUE THREAD

**Issue by gust-tech** [Equipe03-Generation/Dev_Girls_React#3]
Não efetua o cadastro e credenciamento do usuário. Uma revisão na documentação da API para checar as rotas é necessária, além de algumas mudanças e revisões no front-end.

**Comment by Equipe03-Generation** [comment]
Problema resolvido, toda a parte relacionada a cadastro e login foram revisados e atualizados
