### ISSUE TITLE
Navigate dando erro misteriosamente

### ISSUE THREAD

**Issue by Equipe03-Generation** [Equipe03-Generation/Dev_Girls_React#7]
src\paginas\cadastroUsuario\CadastroUsuario.tsx
  Line 37:8:  React Hook useEffect has a missing dependency: 'navigate'. Either include it or remove the dependency array

src\paginas\login\Login.tsx
  Line 34:8:  React Hook useEffect has a missing dependency: 'navigate'. Either include it or remove the dependency array

**Comment by gust-tech** [comment]
Aparentemente o erro desapareceu, caso retorne eu reabro o tópico
